
development:
  adapter: postgresql
  encoding: unicode
  database: mellowgasm_development
  pool: 5
  username: josephwaine
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mellowgasm_test
  pool: 5
  username: josephwaine
  password: