development:
  adapter: postgresql
  encoding: unicode
  database: mellowgasm_development
  pool: 5
  host: localhost
  username: AdiSingh
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mellowgasm_test
  host: localhost
  pool: 5
  username: AdiSingh
  password: